# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'Noah Davis', :email => 'yochibot01@gmail.com', :password => 'lavaland', :password_confirmation => 'lavaland'
puts 'New user created: ' << user.name

puts 'SETTING UP TEST ARTICLES'
article1 = Article.create! :title => 'Fire Safety in the Jungle', :snipit => 'Vestibulum bibendum ligula non metus pharetra mollis. Sed vitae justo libero. Aenean et dolor sem, nec vestibulum tellus. Fusce eu ante ac lorem adipiscing porttitor. Quisque pulvinar tortor quis magna adipiscing ultrices. Morbi scelerisque elit id justo ultrices quis rhoncus metus aliquet. Mauris quis neque ligula. Morbi massa mi, rutrum a malesuada in, dignissim eget lectus. Mauris rutrum sapien id libero sagittis id dictum felis pharetra. Nullam faucibus pellentesque sem, sed accumsan purus tempor vitae. Donec sit amet facilisis nibh. Etiam lacinia massa et velit porttitor egestas mattis ut nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet massa in nisl fringilla porta.', :content => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis velit neque, pharetra sit amet faucibus id, egestas quis mauris. Mauris id sem massa. Nulla leo ipsum, tempus non ultricies eget, aliquet in nisl. Maecenas ultricies dui eu neque tempus faucibus. Vivamus venenatis turpis non est lobortis eu sodales magna fermentum. Suspendisse vitae leo sem. Vestibulum purus tellus, molestie ut aliquam eget, mollis in nibh. Suspendisse in orci quam. Donec in ipsum felis. Sed rutrum, risus congue feugiat suscipit, augue dolor ullamcorper odio, placerat luctus quam elit sed ligula.

Vestibulum bibendum ligula non metus pharetra mollis. Sed vitae justo libero. Aenean et dolor sem, nec vestibulum tellus. Fusce eu ante ac lorem adipiscing porttitor. Quisque pulvinar tortor quis magna adipiscing ultrices. Morbi scelerisque elit id justo ultrices quis rhoncus metus aliquet. Mauris quis neque ligula. Morbi massa mi, rutrum a malesuada in, dignissim eget lectus. Mauris rutrum sapien id libero sagittis id dictum felis pharetra. Nullam faucibus pellentesque sem, sed accumsan purus tempor vitae. Donec sit amet facilisis nibh. Etiam lacinia massa et velit porttitor egestas mattis ut nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet massa in nisl fringilla porta.

Nullam non dolor at nulla elementum aliquet sed id sem. Nunc viverra, mauris eu dapibus convallis, odio mauris vulputate lorem, sed mattis mauris risus a ligula. Donec bibendum, quam et auctor aliquet, mi nisl porta augue, sit amet faucibus turpis tortor ut risus. Sed gravida, diam sed consequat venenatis, augue urna viverra odio, eu tristique mi mauris vitae diam. Vivamus at nunc vestibulum quam bibendum malesuada id eget quam. Fusce sagittis gravida orci, a sodales leo facilisis quis. Morbi lobortis fermentum iaculis.

Vestibulum sed tincidunt lacus. Phasellus ipsum diam, faucibus pulvinar laoreet nec, varius vel ante. Praesent a lacus vel arcu pulvinar placerat in sit amet urna. Nullam nec blandit ante. Phasellus ut ipsum ligula, eu mattis mauris. Sed a mauris nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dui nisl, sodales eget luctus tempus, ornare eget nisi. Aenean fringilla vulputate pharetra. Praesent convallis vulputate elit a commodo. Aliquam scelerisque ornare magna, eget sodales magna faucibus ac. Aenean purus turpis, luctus vitae tincidunt quis, porta id leo. Curabitur varius libero blandit ipsum mattis eu bibendum enim pulvinar. Aenean rhoncus ultrices feugiat. In vehicula felis quis mi pellentesque a vehicula nibh dignissim.

Morbi luctus sodales magna in blandit. Maecenas et felis nulla. Curabitur lacus nisl, volutpat non lacinia blandit, tempus ut felis. Suspendisse potenti. Integer eget ipsum at erat egestas iaculis. Suspendisse dignissim urna ultrices sem sodales suscipit. Sed ut tellus in orci luctus pulvinar. Praesent tincidunt feugiat sollicitudin.

Sed condimentum elementum mattis. Fusce consequat consequat vestibulum. Cras pretium, ligula volutpat aliquam ullamcorper, orci ante faucibus lacus, ac vulputate nunc dolor id erat. In rhoncus ante eget leo mattis eu vulputate enim consequat. Nullam tristique, enim id tempor viverra, velit ante consequat urna, eget rhoncus nisl risus vel leo. Donec vitae leo neque, quis feugiat quam. Mauris dui est, venenatis pretium sodales nec, dignissim eget quam. Suspendisse potenti.

Quisque leo lectus, venenatis eu venenatis nec, viverra quis leo. Vestibulum tincidunt scelerisque quam quis laoreet. Etiam porttitor dolor ut turpis tincidunt et pretium ligula bibendum. Sed posuere leo at massa accumsan consectetur. Mauris at purus sit amet dui eleifend ultrices. Phasellus dapibus tellus vel magna bibendum pellentesque a elementum orci. In hac habitasse platea dictumst. Vivamus euismod facilisis tristique. Mauris pulvinar lacinia purus, in mattis nibh sagittis quis. Phasellus rutrum convallis nisi, sit amet condimentum sapien elementum et. Suspendisse potenti. Quisque gravida porttitor luctus. Praesent tempor tellus vitae dui consectetur venenatis. Nam lorem ante, feugiat non adipiscing sit amet, semper eget odio. Duis vitae lorem metus. Aliquam convallis, nisl ac viverra tempus, justo tortor ullamcorper tellus, iaculis ullamcorper orci dolor eget tellus.

Aliquam erat volutpat. Aenean vitae pulvinar erat. Mauris bibendum sem tortor, eget rhoncus nisi. Nullam molestie consequat tortor ut faucibus. Mauris in felis sed lectus bibendum imperdiet. Nullam eleifend lacus vitae tellus tincidunt ornare. Morbi congue massa a ante imperdiet pulvinar. Nullam id est sem, eu blandit augue. Proin eu dui massa. In sit amet nulla sit amet leo dapibus ultricies. In enim lectus, lacinia sit amet rhoncus in, porttitor vitae ante. Mauris eu tempus neque. Nullam a augue ac magna fringilla commodo. Aliquam mollis pulvinar turpis, ut tincidunt erat sagittis non. Vestibulum sit amet odio quam, eu fringilla nulla. Donec ut ligula elit.', :published => true
article2 = Article.create! :title => 'Dances With Wolves: Gone Wrong!', :snipit => 'Nullam non dolor at nulla elementum aliquet sed id sem. Nunc viverra, mauris eu dapibus convallis, odio mauris vulputate lorem, sed mattis mauris risus a ligula. Donec bibendum, quam et auctor aliquet, mi nisl porta augue, sit amet faucibus turpis tortor ut risus. Sed gravida, diam sed consequat venenatis, augue urna viverra odio, eu tristique mi mauris vitae diam. Vivamus at nunc vestibulum quam bibendum malesuada id eget quam. Fusce sagittis gravida orci, a sodales leo facilisis quis. Morbi lobortis fermentum iaculis.', :content => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis velit neque, pharetra sit amet faucibus id, egestas quis mauris. Mauris id sem massa. Nulla leo ipsum, tempus non ultricies eget, aliquet in nisl. Maecenas ultricies dui eu neque tempus faucibus. Vivamus venenatis turpis non est lobortis eu sodales magna fermentum. Suspendisse vitae leo sem. Vestibulum purus tellus, molestie ut aliquam eget, mollis in nibh. Suspendisse in orci quam. Donec in ipsum felis. Sed rutrum, risus congue feugiat suscipit, augue dolor ullamcorper odio, placerat luctus quam elit sed ligula.

Vestibulum bibendum ligula non metus pharetra mollis. Sed vitae justo libero. Aenean et dolor sem, nec vestibulum tellus. Fusce eu ante ac lorem adipiscing porttitor. Quisque pulvinar tortor quis magna adipiscing ultrices. Morbi scelerisque elit id justo ultrices quis rhoncus metus aliquet. Mauris quis neque ligula. Morbi massa mi, rutrum a malesuada in, dignissim eget lectus. Mauris rutrum sapien id libero sagittis id dictum felis pharetra. Nullam faucibus pellentesque sem, sed accumsan purus tempor vitae. Donec sit amet facilisis nibh. Etiam lacinia massa et velit porttitor egestas mattis ut nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet massa in nisl fringilla porta.

Nullam non dolor at nulla elementum aliquet sed id sem. Nunc viverra, mauris eu dapibus convallis, odio mauris vulputate lorem, sed mattis mauris risus a ligula. Donec bibendum, quam et auctor aliquet, mi nisl porta augue, sit amet faucibus turpis tortor ut risus. Sed gravida, diam sed consequat venenatis, augue urna viverra odio, eu tristique mi mauris vitae diam. Vivamus at nunc vestibulum quam bibendum malesuada id eget quam. Fusce sagittis gravida orci, a sodales leo facilisis quis. Morbi lobortis fermentum iaculis.

Vestibulum sed tincidunt lacus. Phasellus ipsum diam, faucibus pulvinar laoreet nec, varius vel ante. Praesent a lacus vel arcu pulvinar placerat in sit amet urna. Nullam nec blandit ante. Phasellus ut ipsum ligula, eu mattis mauris. Sed a mauris nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dui nisl, sodales eget luctus tempus, ornare eget nisi. Aenean fringilla vulputate pharetra. Praesent convallis vulputate elit a commodo. Aliquam scelerisque ornare magna, eget sodales magna faucibus ac. Aenean purus turpis, luctus vitae tincidunt quis, porta id leo. Curabitur varius libero blandit ipsum mattis eu bibendum enim pulvinar. Aenean rhoncus ultrices feugiat. In vehicula felis quis mi pellentesque a vehicula nibh dignissim.

Morbi luctus sodales magna in blandit. Maecenas et felis nulla. Curabitur lacus nisl, volutpat non lacinia blandit, tempus ut felis. Suspendisse potenti. Integer eget ipsum at erat egestas iaculis. Suspendisse dignissim urna ultrices sem sodales suscipit. Sed ut tellus in orci luctus pulvinar. Praesent tincidunt feugiat sollicitudin.

Sed condimentum elementum mattis. Fusce consequat consequat vestibulum. Cras pretium, ligula volutpat aliquam ullamcorper, orci ante faucibus lacus, ac vulputate nunc dolor id erat. In rhoncus ante eget leo mattis eu vulputate enim consequat. Nullam tristique, enim id tempor viverra, velit ante consequat urna, eget rhoncus nisl risus vel leo. Donec vitae leo neque, quis feugiat quam. Mauris dui est, venenatis pretium sodales nec, dignissim eget quam. Suspendisse potenti.

Quisque leo lectus, venenatis eu venenatis nec, viverra quis leo. Vestibulum tincidunt scelerisque quam quis laoreet. Etiam porttitor dolor ut turpis tincidunt et pretium ligula bibendum. Sed posuere leo at massa accumsan consectetur. Mauris at purus sit amet dui eleifend ultrices. Phasellus dapibus tellus vel magna bibendum pellentesque a elementum orci. In hac habitasse platea dictumst. Vivamus euismod facilisis tristique. Mauris pulvinar lacinia purus, in mattis nibh sagittis quis. Phasellus rutrum convallis nisi, sit amet condimentum sapien elementum et. Suspendisse potenti. Quisque gravida porttitor luctus. Praesent tempor tellus vitae dui consectetur venenatis. Nam lorem ante, feugiat non adipiscing sit amet, semper eget odio. Duis vitae lorem metus. Aliquam convallis, nisl ac viverra tempus, justo tortor ullamcorper tellus, iaculis ullamcorper orci dolor eget tellus.

Aliquam erat volutpat. Aenean vitae pulvinar erat. Mauris bibendum sem tortor, eget rhoncus nisi. Nullam molestie consequat tortor ut faucibus. Mauris in felis sed lectus bibendum imperdiet. Nullam eleifend lacus vitae tellus tincidunt ornare. Morbi congue massa a ante imperdiet pulvinar. Nullam id est sem, eu blandit augue. Proin eu dui massa. In sit amet nulla sit amet leo dapibus ultricies. In enim lectus, lacinia sit amet rhoncus in, porttitor vitae ante. Mauris eu tempus neque. Nullam a augue ac magna fringilla commodo. Aliquam mollis pulvinar turpis, ut tincidunt erat sagittis non. Vestibulum sit amet odio quam, eu fringilla nulla. Donec ut ligula elit.', :published => true
puts 'New Articles Created'
